# Top-level configuration
name = "converter-api"
main = "src/index.js"
compatibility_date = "2024-05-12"

# Add your account_id
# account_id = "your_cloudflare_account_id"

[env.production]
routes = [
    { pattern = "api.convert.rzsite.my.id", custom_domain = true }
]
