# Top-level configuration
name = "converter-api-worker"
main = "src/index.js"
compatibility_date = "2025-09-09"
node_compat = true   # ← enables built-in Node.js modules (punycode, buffer, etc.)


# Add your account_id
# account_id = "your_cloudflare_account_id"

[env.production]
routes = [
    { pattern = "api.convert.rzsite.my.id", custom_domain = true }
]
